Repository angular-medellin/ngcolombia-2018, pull requests merged in 2018-05, with the labels that each got.

#29 [Feat] Update app & cli to Angular V6
  angular.json
  karma.conf.js
  package.json
  src/app/newsletter-signup/newsletter-signup.component.ts
  src/app/welcome/welcome.component.ts
  src/tsconfig.spec.json
  tsconfig.json
  tslint.json
  yarn.lock
Labels: enhancement, in progress

#31 [Feat] Add routing module, update deps & fix lint issues
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/newsletter-signup/newsletter-signup.component.html
  src/app/shared/directives/madness.directive.ts
  src/app/shared/directives/parallax-bigbang.directive.ts
  src/app/shared/directives/parallax-hover.directive.ts
  yarn.lock
Labels: enhancement

#33 feat: Add Speakers lazy loaded module & imports sorting
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/shared/shared.module.ts
  src/app/speakers/speakers-routing.module.ts
  src/app/speakers/speakers.component.spec.ts
  src/app/speakers/speakers.module.spec.ts
  src/app/speakers/speakers.module.ts
Labels: enhancement, in progress

#36 refactor: Change folder structure & styles for full page title
  src/app/app-routing.module.ts
  src/app/speakers/core/speaker-photo.pipe.spec.ts
  src/app/speakers/core/speaker-photo.pipe.ts
  src/app/speakers/core/speaker.model.ts
  src/app/speakers/speakers-bio/speakers-bio.component.html
  src/app/speakers/speakers-bio/speakers-bio.component.ts
  src/app/speakers/speakers-list/speakers-list.component.html
  src/app/speakers/speakers-list/speakers-list.component.scss
  src/app/speakers/speakers-list/speakers-list.component.spec.ts
  src/app/speakers/speakers-list/speakers-list.component.ts
  src/app/speakers/speakers-routing.module.ts
  src/app/speakers/speakers.module.ts
Labels: enhancement, in progress

#38 feat: Add responsiveness to the Speakers page
  src/app/material/material.module.ts
  src/app/speakers/speakers-bio/speakers-bio.component.html
  src/app/speakers/speakers-bio/speakers-bio.component.scss
  src/app/speakers/speakers-list/speakers-list.component.html
  src/app/speakers/speakers-list/speakers-list.component.scss
  src/style/_variables.scss
Labels: enhancement

#34 feat: add sidebar to the right side
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/home/home-banner/home-banner.component.html
  src/app/home/home-banner/home-banner.component.scss
  src/app/home/home-banner/home-banner.component.ts
  src/app/home/home-banner/image-list.model.ts
  src/app/home/home-newsletter/home-newsletter.component.html
  src/app/home/home-newsletter/home-newsletter.component.scss
  src/app/home/home-newsletter/home-newsletter.component.spec.ts
  src/app/home/home-newsletter/home-newsletter.component.ts
  src/app/home/home.module.ts
  src/app/home/home/home.component.html
  src/app/home/home/home.component.scss
  src/app/home/home/home.component.ts
  src/app/shared/directives/parallax-scroll.directive.ts
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.scss
  src/app/shared/header/header.component.ts
  src/app/shared/header/menu/menu.component.css
  src/app/shared/header/menu/menu.component.html
  src/app/shared/header/menu/menu.component.ts
  src/app/shared/menu/menu.component.html
  src/app/shared/menu/menu.component.scss
  src/app/shared/menu/menu.component.spec.ts
  src/app/shared/menu/menu.component.ts
  src/app/shared/shared.module.ts
  src/assets/img/home/learn/BOLITA1_desktop.png
  src/assets/img/home/learn/BOLITA1_mobile.png
  src/assets/img/home/learn/BOLITA2_desktop.png
  src/assets/img/home/learn/BOLITA2_mobile.png
  src/assets/img/home/learn/BOLITA3_desktop.png
  src/assets/img/home/learn/BOLITA3_mobile.png
  src/assets/img/home/meet/BOLITA1_desktop.png
  src/assets/img/home/meet/BOLITA1_mobile.png
  src/assets/img/home/meet/BOLITA2_desktop.png
  src/assets/img/home/meet/BOLITA2_mobile.png
  src/assets/img/home/meet/BOLITA3_desktop.png
  src/assets/img/home/meet/BOLITA3_mobile.png
  src/assets/img/home/share/BOLITA1_desktop.png
  src/assets/img/home/share/BOLITA1_mobile.png
  src/assets/img/home/share/BOLITA2_desktop.png
  src/assets/img/home/share/BOLITA2_mobile.png
  src/assets/img/home/share/BOLITA3_desktop.png
  src/assets/img/home/share/BOLITA3_mobile.png
  src/assets/img/home/share/BOLITA4_desktop.png
  src/assets/img/home/share/BOLITA4_mobile.png
  src/style/ngcolombia.material.scss
  src/styles.scss
  yarn.lock
Labels: in progress
